name: GitHub Pages

on:
  push:
    branches:
      - main  # Oletushaara, muuta tarvittaessa

permissions:
  contents: write # T채m채 on t채rke채 julkaistaessa GitHub Pagesiin

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        run: npm run deploy 